name: freezlotto
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path_provider: ^2.0.2
  provider: ^4.3.2+1
  shared_preferences: ^2.0.6
  fluttertoast: ^7.0.4
  url_launcher: ^6.0.4
  flutter_share: ^2.0.0
  connectivity: ^3.0.6
  dio: ^4.0.0
  modal_progress_hud: ^0.1.3
  video_player: ^2.1.1
  youtube_player_flutter: ^8.0.0
  like_button: ^2.0.3
  image_picker: ^0.8.4+1
  image_cropper: ^1.4.1
  chewie: ^1.0.0
  webview_flutter: ^2.0.13
  mime_type: ^1.0.0
  cached_network_image: ^3.1.0
  http: ^0.13.3
  flutter_spinkit: ^5.1.0
  firebase_dynamic_links: ^2.0.6
#  firebase_core: ^1.6.0
  firebase_core: ^1.7.0
#  firebase_dynamic_links: ^2.0.10
#  firebase_dynamic_links: ^0.6.0
#  firebase_core: ^0.5.0
  getwidget: ^2.0.4
  carousel_slider: ^4.0.0
  get_it: ^6.0.0
  video_thumbnail: ^0.4.3
  flutter_branch_sdk: ^3.4.0
  photo_view: ^0.13.0
  dotted_border: ^1.0.7
  share: ^2.0.1
  velocity_x: ^3.3.0  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: black_font
      fonts:
        - asset: fonts/black_font.ttf
    - family: bold_font
      fonts:
        - asset: fonts/bold_font.ttf
    - family: extra_bold_font
      fonts:
        - asset: fonts/extra_bold_font.ttf
    - family: extra_light_font
      fonts:
        - asset: fonts/extra_light_font.ttf
    - family: light_font
      fonts:
        - asset: fonts/light_font.ttf
    - family: medium_font
      fonts:
        - asset: fonts/medium_font.ttf
    - family: regular_font
      fonts:
        - asset: fonts/regular_font.ttf
    - family: semi_bold_font
      fonts:
        - asset: fonts/semi_bold_font.ttf
    - family: thin_font
      fonts:
        - asset: fonts/thin_font.ttf

  uses-material-design: true
  assets:
    - assets/images/
